type-6:
  clients:
    type-7:
      client-id: ${TYPE6_CLIENT_ID}
      client-secret: ${TYPE6_CLIENT_SECRET}
      client-redirect-uri: ${TYPE6_CLIENT_REDIRECT_URI}
      client-cors-allowed-origin: ${TYPE6_CLIENT_CORS_ALLOWED_ORIGIN}
      auth-method: yandex