type-6:
  clients:
    type-8:
      client-id: ${TYPE8_CLIENT_ID}
      client-secret: ${TYPE8_CLIENT_SECRET}
      client-redirect-uri: ${TYPE8_CLIENT_REDIRECT_URI}
      client-hostname: ${TYPE8_HOSTNAME}
      auth-method: all