type-6:
  clients:
    type-7:
      client-id: ${TYPE7_CLIENT_ID}
      client-secret: ${TYPE7_CLIENT_SECRET}
      client-redirect-uri: ${TYPE7_CLIENT_REDIRECT_URI}
      client-hostname: ${TYPE7_HOSTNAME}
      auth-method: yandex