apiVersion: apps/v1
kind: Deployment
metadata:
  name: type-6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: type-6
  template:
    metadata:
      labels:
        app: type-6
    spec:
      containers:
        - name: type-6
          image: docker.io/timattt/type-6:latest
          imagePullPolicy: Always
          env:
            - name: TYPE6_ENABLE_SSL
              value: "false"
            - name: TYPE6_ACTIVE_PROFILE
              value: "release"
            - name: TYPE6_DATABASE_USER
              value: default-user
            - name: TYPE6_SELF_IP
              value: https://service.shlimtech.org
            - name: TYPE6_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: type-6-basic-secrets
                  key: type_6_database_jdbc_url
            - name: TYPE6_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: type-6-basic-secrets
                  key: type_6_database_password
            - name: TYPE8_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: type-6-basic-secrets
                  key: type_8_client_id
            - name: TYPE8_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: type-6-basic-secrets
                  key: type_8_client_secret
            - name: TYPE8_HOSTNAME
              value: "https://pattern.shlimtech.org"
            - name: TYPE8_CLIENT_REDIRECT_URI
              value: "https://pattern.shlimtech.org/code"
            - name: TYPE6_RABBIT_HOST
              value: rabbitmq.default.svc.cluster.local
            - name: TYPE6_RABBIT_PORT
              value: "15672"
            - name: TYPE6_RABBIT_USERNAME
              value: rabbit
            - name: TYPE6_RABBIT_PASSWORD
              value: rabbit
            - name: TYPE6_GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: type-6-basic-secrets
                  key: type_6_github_client_id
            - name: TYPE6_GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: type-6-basic-secrets
                  key: type_6_github_client_secret
            - name: TYPE6_YANDEX_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: type-6-basic-secrets
                  key: type_6_yandex_client_id
            - name: TYPE6_YANDEX_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: type-6-basic-secrets
                  key: type_6_yandex_client_secret
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/secrets
              readOnly: true
      volumes:
        - name: secret-volume
          secret:
            secretName: type-6-basic-secret-files
