version: '3.4'
name: type-6-local

services:
  postgres:
    container_name: type-6-postgres
    image: postgres:latest
    profiles:
      - local
      - dockerized
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 1s
      timeout: 1s
      retries: 100
    user: postgres
  rabbit:
    container_name: type-6-rabbit
    image: rabbitmq:management
    hostname: rabbitmq
    restart: always
    profiles:
      - local
      - dockerized
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
    ports:
      - "15672:5672"
      - "1567:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
  type-6:
    build:
      context: ./../../.
      dockerfile: ./Dockerfile
    profiles:
      - dockerized
    environment:
      SPRING_PROFILES_ACTIVE: dockerized
    ports:
      - "7777:7777"
    depends_on:
      - postgres
      - rabbit
    volumes:
      - "./../../TypeSixWeb/src/test/resources/keys:/tmp/keys"