type-6:
  clients:
    type-8:
      client-id: ${TYPE8_CLIENT_ID}
      client-secret: ${TYPE8_CLIENT_SECRET}
      client-redirect-uri: "https://pattern.mipt.io/code"
      client-hostname: "https://pattern.mipt.io"
      auth-method: all
    type-12:
      client-id: ${TYPE12_CLIENT_ID}
      client-secret: ${TYPE12_CLIENT_SECRET}
      client-redirect-uri: "https://messenger.mipt.io/code"
      client-hostname: "https://messenger.mipt.io"
      auth-method: all