version: '3.4'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${TYPE6_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TYPE6_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 1s
      timeout: 1s
      retries: 100
    user: postgres
  rabbit:
    image: rabbitmq:management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${TYPE6_RABBIT_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${TYPE6_RABBIT_PASSWORD}
    ports:
      - "15672:5672"
      - "1567:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s