version: '3.4'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${TYPE6_DATABASE_USER}
      POSTGRES_PASSWORD: ${TYPE6_DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 1s
      timeout: 1s
      retries: 100
    user: postgres
  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${TYPE6_RABBIT_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${TYPE6_RABBIT_PASSWORD}
    ports:
      - "15672:5672"
      - "1567:15672"
  redis:
    image: redis:latest
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass ${TYPE6_REDIS_PASSWORD}
    ports:
      - '6379:6379'