name: deploy-type-6

on:
  workflow_dispatch:
  push:
    branches:
      - "release"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: type-6
          tags: latest
          containerfiles: ./Dockerfile

      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: type-6
          tags: latest
          registry: quay.io/timattt
          username: timattt
          password: ${{ secrets.QUAY_REGISTRY_PASSWORD }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: bitnami/kubectl
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Run k8s
        run: |
          kubectl config set-cluster k8s --server=${{ secrets.KUBERNETES_URL }} --insecure-skip-tls-verify=true
          kubectl config set-credentials admin --token=${{ secrets.KUBERNETES_SECRET }}
          kubectl config set-context default --cluster=k8s --user=admin
          kubectl config use-context default          
          kubectl get pod -A
          kubectl delete --ignore-not-found=true -f scripts/k8s/type-6.yaml
          kubectl apply -f scripts/k8s/type-6.yaml
          kubectl get pod -A
  jmeter_single_oauth2_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run JMeter Tests
        uses: QAInsights/PerfAction@v5.6.2
        with:
          test-plan-path: scripts/test/jmeter/type-6-single-oauth2-test-scenario.jmx
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: result.jtl
      - name: Analyze Results with Latency Lingo
        uses: latency-lingo/github-action@v0.0.2
        with:
          api-key: ${{ secrets.LATENCY_LINGO_API_KEY }}
          file: result.jtl
          label: Type-6 single oauth2 flow test
          format: jmeter