name: test-single-oauth2

on:
  workflow_dispatch:
  push:
    branches:
      - "test"

jobs:
  action_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run JMeter Tests
        uses: QAInsights/PerfAction@v5.6.2
        with:
          test-plan-path: scripts/test/jmeter/type-6-single-oauth2-test-scenario.jmx
          args: "-JclientId=\"${{ secrets.TEST_CLIENT_ID }}\" -Jauth=\"${{ secrets.TEST_AUTH }}\" -JredirectUrl=\"https://pattern.mipt.io/code\" -Jemail=\"service@mipt.io\" -Jpassword=biba -Jhost=sso.mipt.io"
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: result.jtl
