name: test-single-oauth2

on:
  workflow_dispatch:
  push:
    branches:
      - "test"

jobs:
  action_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run JMeter Action on a test
        uses: rbhadti94/apache-jmeter-action@v0.7.0
        with:
          testFilePath: scripts/test/jmeter/type-6-single-oauth2-test-scenario.jmx
          outputReportsFolder: reports/
          args: "--loglevel INFO \
                  -JclientId=\"${{ secrets.TEST_CLIENT_ID }}\" \
                  -Jauth=\"${{ secrets.TEST_AUTH }}\" \
                  -JredirectUrl=https://pattern.mipt.io/code \
                  -Jemail=service@mipt.io \
                  -Jpassword=biba \
                  -Jhost=sso.mipt.io \
                  -Jprotocol=https \
                  -Jport=443"
      - name: Print the final result
        shell: bash
        run: |
          ls reports