name: test-type-6

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      short_message: ${{ steps.results.outputs.short_message }}
      long_message: ${{ steps.results.outputs.long_message }}
    container:
      image: justb4/jmeter
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        id: results
        run: |
          apk add --no-cache python3
          jmeter -n -t scripts/test/jmeter/type-6-single-oauth2-test-scenario.jmx -l result.csv
          export LONG_MESSAGE=$(python3 scripts/test/python/parser_script.py result.csv)
          export SHORT_MESSAGE=$(python3 scripts/test/python/tag_name_generator.py result.csv)
          echo "short_message=${SHORT_MESSAGE}" >> "$GITHUB_OUTPUT"
          echo "long_message=${LONG_MESSAGE}" >> "$GITHUB_OUTPUT"
  create_tag:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v4
    - uses: rickstaa/action-create-tag@v1
      with:
        tag: ${{ needs.test.outputs.short_message }}
        force_push_tag: true
        message: ${{ needs.test.outputs.long_message }}

