name: test-type-6

on:
  workflow_dispatch:

jobs:
  action_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: negz/create-tag@v1
        with:
          # Github Token
          token: ${{ secrets.GITHUB_TOKEN }}
          # Version (e.g. v0.1.0)
          version: test
          # Tag message
          message: biba
      - name: Run JMeter Action on a test
        uses: rbhadti94/apache-jmeter-action@v0.7.0
        with:
          testFilePath: scripts/test/jmeter/type-6-single-oauth2-test-scenario.jmx
          outputReportsFolder: reports/
      - name: Print the final result
        shell: bash
        run: |
          export TOTAL_RPS=$(cat reports/statistics.json | jq -r '.Total.throughput')
          export SAMPLE_COUNT=$(cat reports/statistics.json | jq -r '.Total.sampleCount')
          export ERROR_COUNT=$(cat reports/statistics.json | jq -r '.Total.errorCount')
          echo "$TOTAL_RPS"

