name: test-type-6

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: justb4/jmeter
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        id: results
        run: |
          apk add --no-cache python3
          export MESSAGE=$(jmeter -n -t scripts/test/jmeter/type-6-single-oauth2-test-scenario.jmx -l result.csv && python3 scripts/test/python/parser_script.py result.csv)
          echo "message=RPS: ${MESSAGE}" >> "$GITHUB_OUTPUT"
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "single_oauth2_flow_load_testing"
          force_push_tag: true
          message: ${{ steps.results.outputs.message }}

