name: test-type-6

on:
  workflow_dispatch:

jobs:
  action_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run JMeter Action on a test
        uses: rbhadti94/apache-jmeter-action@v0.7.0
        with:
          testFilePath: scripts/test/jmeter/type-6-single-oauth2-test-scenario.jmx
          outputReportsFolder: reports/
      - name: Print the final result
        shell: bash
        run: |
          ls reports
          ls reports/content
          cat reports/statistics.json
          cat reports/index.html
          nproc --all
          free -g -h -t
